<a href="https://colab.research.google.com/github/pavithra64/air-bnb-bookings/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **AIRBNB BOOKINGS ANALYSIS**

**PROJECT TYPE**: EDA

**CONTRIBUTION**: INDIVIDUAL

# INTRODUCTION

Since 2008, guests and hosts have used Airbnb to expand on traveling possibilities and present a more unique, personalized way of experiencing the world. Today, Airbnb became one of a kind service that is used and recognized by the whole world. Data analysis on millions of listings provided through Airbnb is a crucial factor for the company. These millions of listings generate a lot of data - data that can be analyzed and used for security, business decisions, understanding of customers' and providers' (hosts) behavior and performance on the platform, guiding marketing initiatives, implementation of innovative additional services and much more.
This dataset has around 49,000 observations in it with 16 columns and it is a mix between categorical and numeric values.

__Explore and analyze the data to discover key understandings (not limited to these) such as :__

What can we learn about different hosts and areas?

1.   What can we learn from predictions? (ex: locations, prices, reviews, etc)
2.   Which hosts are the busiest and why?
3.   Is there any noticeable difference of traffic among different areas and what could be the reason for it?

*AIRBNB is an American company that operates an online marketplace for lodging, primarily homestays for vacation rentals, and tourism activities. Based in San Francisco, California, the platform is accessible via website and mobile app. Airbnb does not own any of the listed properties; instead, it profits by receiving commission from each booking. The company was founded in 2008 by Brian Chesky, Nathan Blecharczyk and Joe Gebbia. Airbnb is a shortened version of its original name, AirBedandBreakfast.com.*

**IMPORTING LIBRARIES**

In [9]:
#Importing all Necessary Libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime
import plotly.express as px
from shapely.geometry import Point,Polygon
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from shapely import wkt
import warnings
warnings.filterwarnings(action='ignore')
%matplotlib inline

**LOAD THE DATA**

In [11]:

from google.colab import files
uploaded=files.upload()

Saving Airbnb NYC 2019.csv to Airbnb NYC 2019 (1).csv

In [6]:
airbnb="Airbnb NYC 2019.csv"
airbnb_df=pd.read_csv(airbnb)

**KNOW YOUR DATA**

In [7]:
#head of airbnb_df
airbnb_df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,19-10-2018,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,21-05-2019,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,05-07-2019,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19-11-2018,0.10,1,0

In [8]:
#tail of airbnb_df
airbnb_df.tail()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23

In [12]:
#checking the size of the airbnb_df
airbnb_df.size

782320

In [ ]:
#checking shape of airbnb_df
airbnb_df.shape

(48895, 16)

In [ ]:
#description
airbnb_df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.889500e+04,4.889500e+04,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000,38843.000000,48895.000000,48895.000000
mean,1.901714e+07,6.762001e+07,40.728949,-73.952170,152.720687,7.029962,23.274466,1.373221,7.143982,112.781327
std,1.098311e+07,7.861097e+07,0.054530,0.046157,240.154170,20.510550,44.550582,1.680442,32.952519,131.622289
min,2.539000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.471945e+06,7.822033e+06,40.690100,-73.983070,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.967728e+07,3.079382e+07,40.723070,-73.955680,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,2.915218e+07,1.074344e+08,40.763115,-73.936275,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,3.648724e+07,2.743213e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

In [14]:
len(airbnb_df)

48895

**CHECKING THE NULL VALUES IN THE DATA**

In [ ]:
#checking null values or unknown data
airbnb_df.isnull().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [ ]:
#getting the columns which are required for analysis of hosts
airbnb_df_new=airbnb_df.loc[:,['host_id','host_name','price','number_of_reviews','reviews_per_month','availability_365','neighbourhood_group','neighbourhood']]
airbnb_df_new

,host_id,host_name,price,number_of_reviews,reviews_per_month,availability_365,neighbourhood_group,neighbourhood
0,2787,John,149,9,0.21,365,Brooklyn,Kensington
1,2845,Jennifer,225,45,0.38,355,Manhattan,Midtown
2,4632,Elisabeth,150,0,NaN,365,Manhattan,Harlem
3,4869,LisaRoxanne,89,270,4.64,194,Brooklyn,Clinton Hill
4,7192,Laura,80,9,0.10,0,Manhattan,East Harlem
...,...,...,...,...,...,...,...,...
48890,8232441,Sabrina,70,0,NaN,9,Brooklyn,Bedford-Stuyvesant
48891,6570630,Marisol,40,0,NaN,36,Brooklyn,Bushwick
48892,23492952,Ilgar & Aysel,115,0,NaN,27,Manhattan,Harlem
48893,30985759,Taz,55,0,NaN,2,Manhattan,Hell's Kitchen
48894,68119814,Christophe,90,0,NaN,23,Manhattan,Hell's Kitchen

In [ ]:
#handling missing values
airbnb_df_new.fillna({'reviews_per_month':0}, inplace=True)
airbnb_df_new.dropna(subset=['host_name'],inplace=True)

In [ ]:
#length of new airbnb_df
len(airbnb_df_new)

48874

In [ ]:
#checking null values or missing data
airbnb_df_new.isnull().sum()

host_id                0
host_name              0
price                  0
number_of_reviews      0
reviews_per_month      0
availability_365       0
neighbourhood_group    0
neighbourhood          0
dtype: int64

In [ ]:
#we have clean data now
print(type(airbnb_df_new["host_id"]))
print(type(airbnb_df_new['host_name']))
print(type(airbnb_df_new["availability_365"]))
print(type(airbnb_df_new["number_of_reviews"]))
print(type(airbnb_df_new["reviews_per_month"]))
print(type(airbnb_df_new["price"]))
print(type(airbnb_df_new['neighbourhood_group']))
print(type(airbnb_df_new['neighbourhood']))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

In [ ]:
#head of airbnb_df_new
airbnb_df_new.head()

,host_id,host_name,price,number_of_reviews,reviews_per_month,availability_365,neighbourhood_group,neighbourhood
0,2787,John,149,9,0.21,365,Brooklyn,Kensington
1,2845,Jennifer,225,45,0.38,355,Manhattan,Midtown
2,4632,Elisabeth,150,0,0.00,365,Manhattan,Harlem
3,4869,LisaRoxanne,89,270,4.64,194,Brooklyn,Clinton Hill
4,7192,Laura,80,9,0.10,0,Manhattan,East Harlem

In [ ]:
#tail of airbnb_df_new
airbnb_df_new.tail()

,host_id,host_name,price,number_of_reviews,reviews_per_month,availability_365,neighbourhood_group,neighbourhood
48890,8232441,Sabrina,70,0,0.0,9,Brooklyn,Bedford-Stuyvesant
48891,6570630,Marisol,40,0,0.0,36,Brooklyn,Bushwick
48892,23492952,Ilgar & Aysel,115,0,0.0,27,Manhattan,Harlem
48893,30985759,Taz,55,0,0.0,2,Manhattan,Hell's Kitchen
48894,68119814,Christophe,90,0,0.0,23,Manhattan,Hell's Kitchen

__Find the top 10 most reviewed listings based on number of reviews per month__.

In [ ]:
# Let us find top 10 most reviewed listings based on number of reviews per month.
most_reviewed_listings=airbnb_df.nlargest(10,'number_of_reviews')
most_reviewed_listings
reviewed_per_listings= airbnb_df.filter(['neighbourhood_group','number_of_reviews'])
reviewed_per_listings
top_reviewed_listings=reviewed_per_listings.nlargest(10,'number_of_reviews')
top_reviewed_listings

      neighbourhood_group  number_of_reviews
11759              Queens                629
2031            Manhattan                607
2030            Manhattan                597
2015            Manhattan                594
13495              Queens                576
10623              Queens                543
1879            Manhattan                540
20403              Queens                510
4870             Brooklyn                488
471              Brooklyn                480

__Is the number_of_reviews have any effect on traffic in particular area?__

In [ ]:
# Let us check whether number_of_reviews have any effect on traffic in particular area.
maximum_reviews=airbnb_df.groupby(['neighbourhood']).number_of_reviews.sum()
maximum_reviews=maximum_reviews.sort_values(ascending=False)
maximum_reviews

neighbourhood
Bedford-Stuyvesant            110352
Williamsburg                   85427
Harlem                         75962
Bushwick                       52514
Hell's Kitchen                 50227
                               ...
Breezy Point                       5
Bay Terrace, Staten Island         3
New Dorp                           0
Woodrow                            0
Fort Wadsworth                     0
Name: number_of_reviews, Length: 221, dtype: int64

From the output, we infer that number_of_reviews have strong impact on traffic among different area.



# Which host has the highest number of reviews?

In [ ]:
groupby_host_id_and_host_name=airbnb_df_new.groupby(['host_id','host_name']).sum()[['number_of_reviews']].reset_index()
highest_number_of_reviews=groupby_host_id_and_host_name.sort_values('number_of_reviews',ascending=False).head(10)

In [ ]:
#Replacing hostid with hypen symbol at end of each id. Because Plotly assumes it has integer
highest_number_of_reviews['host_id']=highest_number_of_reviews['host_id'].astype('string')

In [ ]:
#plotting bar graph and styling with pattern shape
fig = px.bar(highest_number_of_reviews, y='number_of_reviews', x='host_name', text='number_of_reviews',
             color='host_id')

In [ ]:
#Updating traces and layout
fig.update_traces(textfont=dict(size=15,color='black'))
fig.update_layout(title='Host has the highest number of reviews')
fig.show()

From above plot we infer that:

___Maya___ has the ___highest number of reviews___ with 2273.

___Brooklyn and Breakfast Len___ is the ___Second highest___ number of reviews with 2205.

# Which host has the highest number of reviews per month?

In [ ]:
#Grouping host_id and host_name and perform sum aggregation function
groupby_host_id_and_host_name=airbnb_df_new.groupby(['host_id','host_name']).sum()[['reviews_per_month']].reset_index()
highest_number_of_reviews_per_month=groupby_host_id_and_host_name.sort_values('reviews_per_month',ascending=False).head(10)
highest_number_of_reviews_per_month['reviews_per_month']=highest_number_of_reviews_per_month['reviews_per_month']

In [ ]:
#plotting bar graph and setting continuous color sclae
fig = px.bar(highest_number_of_reviews_per_month, y='reviews_per_month', x='host_name',text='reviews_per_month',color='reviews_per_month')

In [ ]:
#Updating traces and layout
fig.update_traces(textfont=dict(size=15,color='white'))
fig.update_layout(title='Host has the highest number of reviews per month')

From above plot we infer that:

___Sonder (NYC)___ has the ___highest number___ of reviews per month.
The ___next three highest___ number of reviews per month hosts are ___Row NYC, Lakshmee and Danielle___.

#___Which is the most cheapest area? Show the prize distribution.___

In [ ]:
#Extracing the columns which is required for analysis of area
new_airbnb_df=airbnb_df_new.loc[:,['neighbourhood_group','neighbourhood','price',]]

In [ ]:
#Grouping the Neighborhood group of cheapest area and perofrm mean aggregation function
result_bronx=new_airbnb_df.groupby(['neighbourhood_group','neighbourhood'])['price'].mean().reset_index()
result_bronx['price']=result_bronx['price']
result_bronx=result_bronx.loc[result_bronx['neighbourhood_group']=='Bronx']
result_bronx=result_bronx[['neighbourhood','price']]

In [ ]:
#Sorting the results
result_bronx.sort_values('price',ascending=False,inplace=True)

In [ ]:
#Computing Cumulative Percentage
result_bronx['cum_percent'] = 100*(result_bronx['price'].cumsum() / result_bronx['price'].sum())

In [ ]:
#plotting bar graph price vs neighbourhood_group
trace1 = go.Bar(
    x=result_bronx['neighbourhood'],
    y=result_bronx['price'],text=result_bronx['price'],
    name='price')

In [ ]:
#plotting Scatter graph cumulative percent vs neighbourhood_group
trace2 = go.Scatter(
    x=result_bronx['neighbourhood'],y=result_bronx['cum_percent'], name='cum_percent',yaxis='y2')

In [ ]:
#Merging the two plots to get parreto chart and finding the most cheapest area
fig = make_subplots(specs=[[{"secondary_y": True}]])

In [ ]:
#Updating traces and layout to beautify the plot and setting the font size
fig.add_trace(trace1)
fig.add_trace(trace2,secondary_y=True)
fig['layout'].update(height = 800, width = 1600,xaxis=dict(
      tickangle=-90
    ))
fig.update_layout(title='Bronx is Cheapest area and Average Price distribution of that area',plot_bgcolor='black',xaxis=dict(tickfont = dict(size=14)))
#show figure
fig.show()

From above plot we infer that:

***___Hunts point___ is the ___cheapest___ one with price of room is 50.5.***

___Riverdale___ is the ___most expensive___ one in the ___Bronx___ with average price of room is 442.09. which contribute 9.84% of price distribution from total Bronx neighborhood place of 100% price distribution.


___Riverdale,City Island,Spuyten Duyvil,Eastchester,Unionport,Westchester square and West Farms___ cumulative price percentage is __28.79%__ which lies in total Bronx neighborhood place price distribution of __100%__.


#___Which is the most expensive area and show the price distribution?___

In [ ]:
#Grouping the Neighborhood group of expensive area and perform mean aggregation function
result_manhattan=new_airbnb_df.groupby(['neighbourhood_group','neighbourhood'])['price'].mean().reset_index()
result_manhattan['price']=result_manhattan['price']

In [ ]:
#Sorting the results
result_manhattan=result_manhattan.loc[result_manhattan['neighbourhood_group']=='Manhattan']
result_manhattan=result_manhattan[['neighbourhood','price']]
result_manhattan.sort_values('price',ascending=False,inplace=True)

In [ ]:
# Computing Cumulative Percentage
result_manhattan['cum_percent'] = 100*(result_manhattan['price'].cumsum() / result_manhattan['price'].sum())

In [ ]:
#plotting bar graph price vs neighbourhood_group
trace1 = go.Bar(
    x=result_manhattan['neighbourhood'],
    y=result_manhattan['price'],text=result_manhattan['price'],
    name='price')

In [ ]:
#Merging those two plots to get parreto chart and finding the most expensive area
fig = make_subplots(specs=[[{"secondary_y": True}]])

In [ ]:
#Updating traces and layout to beautify the plot and setting the font size
fig.add_trace(trace1)
fig.add_trace(trace2,secondary_y=True)
fig['layout'].update(height = 800, width = 1400,xaxis=dict(
      tickangle=-90
    ))
fig.update_layout(title='Average Price distribution of Expensive areas in Manhattan Neighborhood',autosize=False,plot_bgcolor='black',xaxis=dict(tickfont = dict(size=14)))
#show figure
fig.show()

From above plot, we infer that:

___Tribecca___ is the ___most expensive___ one in the ___Manhattan___ with average price of room is 490.64. which contribute 7.22% of price distribution from total Manhattan neighborhood place of 100% price distribution.

___Inwood___ is the ___cheapest___ one with price of room is 88.9.

___Tribecca,Battery park city,Flatiron District,NoHo and SoHo___ cumulative price percentage is 26.24%.Which lies in total Manhattan neighborhood place price distribution of 100%.